#!/bin/sh

#set -e -x

# Create directories and define environment variables
mkdir -p $SNAP_COMMON/usb
mkdir -p $SNAP_COMMON/cups
mkdir -p $SNAP_COMMON/pnm2ppa
mkdir -p $SNAP_COMMON/foo2zjs
export BACKEND_DIR=$SNAP/usr/lib/ghostscript-printer-app/backend
export USB_QUIRK_DIR=$SNAP_COMMON
export CUPS_SERVERROOT=$SNAP_COMMON/cups

# Initialize config files of the CUPS backends
cp $BACKEND_DIR/*.usb-quirks $USB_QUIRK_DIR/usb 2>/dev/null || :
if [ ! -f $CUPS_SERVERROOT/snmp.conf ]; then
    cp $BACKEND_DIR/snmp.conf $CUPS_SERVERROOT 2>/dev/null || :
fi
# Initialize config file for pnm2ppa
if [ ! -f $SNAP_COMMON/pnm2ppa/pnm2ppa.conf ]; then
    cp $SNAP/etc/pnm2ppa.conf $SNAP_COMMON/pnm2ppa 2>/dev/null || :
fi
# Initialize color profile directories of foo2zjs
for d in $SNAP/usr/share/foo2*; do
    yes n | cp -ri $d $SNAP_COMMON/foo2zjs/ 2>/dev/null || :
done

exec $SNAP/scripts/run-ghostscript-printer-app -o log-file=$SNAP_COMMON/ghostscript-printer-app.log server "$@"
#exec $SNAP/scripts/run-ghostscript-printer-app -o log-level=debug -o log-file=$SNAP_COMMON/ghostscript-printer-app.log server "$@"
