name: CI Pipeline for ghostcript-printer-app

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-rock:
    strategy:
      matrix:
        include:
        - arch: 'amd64'
          runner: ubuntu-22.04
        - arch: 'arm64'
          runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pack with Rockcraft
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

  build-snap:
    strategy:
      matrix:
        include:
        - arch: 'amd64'
          runner: ubuntu-22.04
        - arch: 'arm64'
          runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Snap Package
        uses: snapcore/action-build@v1
        id: snapcraft
